### ISSUE TITLE
Elastyczna wysokość w listView w konsultacjach studenta

### ISSUE THREAD

**Issue by ZielaA** [DamboySytesNet/mobile#23]

**Comment by Karbowskii** [comment]
Rozwiązanie na branchu "add_employee_consultation" w commicie "Fix row height - nested listView ". Może nie ma fajerwerków ale działa.

**Comment by ZielaA** [comment]
Fajnie, że zamknąłeś sobie issue, ale to dotyczyło akurat konsultacji studenta, a nie pracownika, a tam nadal to nie jest zrobione.

**Comment by Karbowskii** [comment]
XDDD
