### ISSUE TITLE
Konsultacje studenta

### ISSUE THREAD

**Issue by DamboySytesNet** [DamboySytesNet/mobile#4]
Tutaj trzeba zrobić design + pobranie z bazy
- [x] front (tylko top bar)
- [x] pobranie z kokpitu konsultacji, które należą do danego studenta
- [x] wyświetlenie listy konsultacji (bez pięknego frontu)
- [x] posortować je tak żeby były jak najbardziej intuicyjnie

**Comment by ZielaA** [comment]
To jest zbyt wczesny etap projektu, aby już łączyć się z bazą danych. Proponuję utworzyć testową listę konsultacji dla studenta i na niej na razie pracować. Podmienienie tego na wczytywanie z bazy danych będzie osobnym taskiem, gdy baza oraz mechanika będzie gotowa. Robiąc to zadanie trzeba mieć w głowie tę podmianę w przyszłości, aby nie przerabiać później całego kodu, tylko część gdzie przypisujemy dane po etapie logowania.
